package jboss2;
// Generated 3 feb. 2021 16:22:37 by Hibernate Tools 5.4.12.Final

/**
 * EmpleadosId generated by hbm2java
 */
public class EmpleadosId implements java.io.Serializable {

	private String nombre;
	private String apellidos;
	private Double salario;
	private Integer codeDept;

	public EmpleadosId() {
	}

	public EmpleadosId(String nombre, String apellidos, Double salario, Integer codeDept) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.salario = salario;
		this.codeDept = codeDept;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Double getSalario() {
		return this.salario;
	}

	public void setSalario(Double salario) {
		this.salario = salario;
	}

	public Integer getCodeDept() {
		return this.codeDept;
	}

	public void setCodeDept(Integer codeDept) {
		this.codeDept = codeDept;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmpleadosId))
			return false;
		EmpleadosId castOther = (EmpleadosId) other;

		return ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
				&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getApellidos() == castOther.getApellidos()) || (this.getApellidos() != null
						&& castOther.getApellidos() != null && this.getApellidos().equals(castOther.getApellidos())))
				&& ((this.getSalario() == castOther.getSalario()) || (this.getSalario() != null
						&& castOther.getSalario() != null && this.getSalario().equals(castOther.getSalario())))
				&& ((this.getCodeDept() == castOther.getCodeDept()) || (this.getCodeDept() != null
						&& castOther.getCodeDept() != null && this.getCodeDept().equals(castOther.getCodeDept())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getApellidos() == null ? 0 : this.getApellidos().hashCode());
		result = 37 * result + (getSalario() == null ? 0 : this.getSalario().hashCode());
		result = 37 * result + (getCodeDept() == null ? 0 : this.getCodeDept().hashCode());
		return result;
	}

}
